apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: modtl-model
spec:
  predictor:
    containers:
      - name: kserve-container
        image: mariotrivinor/modtl-tool:v11
        imagePullPolicy: Always 
        envFrom:
        - secretRef:
            name: mqtt
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: 8Gi
            cpu : 8
